"""The third-octave filter bank: declared, self-describing, and measured.

Ledger row AC-19. The defect is not that the bank is wrong — energy conservation
within the covered range is exact and the leakage is common-mode across legs, so
paired metrics survive it. The defect is that three consequential properties were
UNDECLARED:

  * the five lowest bands hold ONE FFT bin each at production framing, so they
    measure Hann leakage rather than band content;
  * dropping under-resolved bands makes `center_freqs` an IRREGULAR series that
    still reads as a third-octave ladder;
  * ~6 % of a white-noise IR's STFT power lands in no band at all.

These tests pin the CURRENT behaviour with numbers attached, so that changing the
band floor is a visible, deliberate diff rather than a silent methodology shift.
"""
from pathlib import Path

import numpy as np
import pytest
import torch

from amcd.config import Config
from amcd.representations import build_representation
from amcd.representations.spectrogram import _build_third_octave_filters

from tests.conftest import EVAL_FREQS, tiny_config

_BASE = Path("configs/base.yaml")


@pytest.fixture(scope="module")
def production_rep():
    """The bank as base.yaml actually builds it — 48 kHz, n_fft 2048."""
    cfg = Config.load(_BASE)
    return build_representation(
        cfg.representation.name, cfg.representation.params,
        sample_rate=cfg.sample_rate, eval_freqs_hz=EVAL_FREQS,
    )


def _band_index(rep, centre_hz: float) -> int:
    """Index of the band nearest `centre_hz`.

    The ladder is generated by repeated multiplication by 2^(1/3), so a nominal
    centre like 500 Hz is 499.9999... and exact lookup would fail on arithmetic
    rather than on behaviour.
    """
    idx = int(np.argmin(np.abs(np.array(rep.center_freqs) - centre_hz)))
    assert rep.center_freqs[idx] == pytest.approx(centre_hz, rel=1e-3)
    return idx


def _band_fractions(rep, freq_hz: float) -> np.ndarray:
    """Per-band share of a steady tone's STFT power, edge frames discarded."""
    n = rep.n_fft * 8
    t = torch.arange(n, dtype=torch.float64) / rep.sample_rate
    tone = torch.sin(2.0 * torch.pi * freq_hz * t).float()
    stft = torch.stft(
        tone, n_fft=rep.n_fft, hop_length=rep.hop_length,
        window=rep._window, return_complex=True, center=True,
    )
    edge = max(1, rep.n_fft // (2 * rep.hop_length) + 1)
    power = stft[:, edge:-edge].abs().pow(2).sum(dim=1)
    return (rep._filter_bank * power).sum(dim=1).numpy() / float(power.sum())


class TestLadderIsDeclaredNotHardcoded:
    """Every constant that shapes the ladder is a config value."""

    def test_params_are_required_with_no_defaults(self) -> None:
        from amcd.representations.spectrogram import ThirdOctaveSpectrogram

        for field in ("reference_freq_hz", "bands_per_octave",
                      "min_center_freq_hz", "min_bins_per_band"):
            assert ThirdOctaveSpectrogram.Params.model_fields[field].is_required()

    @pytest.mark.parametrize(
        "field, value",
        [
            ("reference_freq_hz", 0.0),      # `0 * half_width <= nyquist` forever
            ("min_center_freq_hz", 0.0),     # descending `f /= ratio` underflows to 0
            ("bands_per_octave", -3),        # ratio < 1: ascending loop never ends
        ],
    )
    def test_a_ladder_setting_that_would_hang_is_rejected_at_load(
        self, field: str, value: float
    ) -> None:
        """AC-32: three SCHEMA-VALID settings made the construction loop run
        forever — verified with a 3 s alarm. Not a wrong result: a hang or an OOM
        at preprocess, i.e. AFTER the render it would waste. The bound must be in
        `Params`, so the failure is a config-load error, not a stalled run.

        The baseline params come from `tiny_config()` rather than from literals
        here (F-M10). A hand-written dict drifts from the schema — when
        `min_db_headroom_octave_centres_hz` was added, the literal version still
        raised ValidationError but for the MISSING key rather than the field under
        test, so every case passed for the wrong reason. The guard below pins that:
        the baseline must itself be valid before a field is corrupted."""
        from pydantic import ValidationError

        from amcd.representations.spectrogram import ThirdOctaveSpectrogram

        params = dict(tiny_config().representation.params)
        # If this raises, the baseline has drifted from the schema and every
        # parametrized case below would pass without exercising `field` at all.
        ThirdOctaveSpectrogram.Params(**params)

        params[field] = value
        with pytest.raises(ValidationError):
            ThirdOctaveSpectrogram.Params(**params)

    @pytest.mark.parametrize(
        "sample_rate, n_fft, expected_bands",
        [(48000, 2048, 27), (48000, 512, 21), (44100, 2048, 27), (8000, 256, 18)],
    )
    def test_band_count_is_pinned_per_sample_rate(
        self, sample_rate: int, n_fft: int, expected_bands: int
    ) -> None:
        """F-59: the Nyquist admission rule is behaviour-preserving only at 48 kHz.

        The old rule (`f <= sample_rate/2 * 1.01`) gave 27 / 21 / 28 / 19 for these
        four framings; the current rule gives 27 / 21 / 27 / 18. The two disagree
        AWAY from 48 kHz, and at 44.1 kHz that leaves 17959.4-22050 Hz in no band,
        passed through `decode()` unshaped at scale 1.0. Pinned per sample rate so
        the dependence is asserted rather than implied.
        """
        bank, _ = _build_third_octave_filters(
            n_fft, sample_rate, reference_freq_hz=1000.0, bands_per_octave=3,
            min_center_freq_hz=10.0, min_bins_per_band=1,
        )
        assert bank.shape[0] == expected_bands

    def test_bands_per_octave_actually_changes_the_ladder(self) -> None:
        """Not a decorative knob: 1 gives the ISO octave ladder."""
        cfg = tiny_config()
        params = dict(cfg.representation.params)
        third = build_representation("spectrogram", params, sample_rate=48000, eval_freqs_hz=EVAL_FREQS)
        params["bands_per_octave"] = 1
        octave = build_representation("spectrogram", params, sample_rate=48000, eval_freqs_hz=EVAL_FREQS)
        assert octave.n_bands < third.n_bands
        assert 1000.0 in octave.center_freqs  # the reference anchors both ladders

    def test_no_band_may_straddle_nyquist(self) -> None:
        """The upper bound is derived from Nyquist, not a `* 1.01` fudge factor.

        A band whose upper edge sits above Nyquist is half-empty by construction
        and would be reported as a real measurement.
        """
        cfg = Config.load(_BASE)
        rep = build_representation(
            cfg.representation.name, cfg.representation.params,
            sample_rate=cfg.sample_rate, eval_freqs_hz=EVAL_FREQS,
        )
        for lo, hi in rep.band_description["band_edges_hz"]:
            assert hi <= cfg.sample_rate / 2.0, f"band [{lo}, {hi}] exceeds Nyquist"

    def test_min_bins_per_band_below_one_is_rejected(self) -> None:
        cfg = tiny_config()
        params = dict(cfg.representation.params, min_bins_per_band=0)
        with pytest.raises(ValueError, match="min_bins_per_band"):
            build_representation("spectrogram", params, sample_rate=48000, eval_freqs_hz=EVAL_FREQS)

    def test_an_impossible_band_floor_fails_loudly(self) -> None:
        """Rather than returning an empty bank and failing later on a shape."""
        with pytest.raises(ValueError, match="no band survived"):
            _build_third_octave_filters(
                64, 48000, reference_freq_hz=1000.0, bands_per_octave=3,
                min_center_freq_hz=10.0, min_bins_per_band=500,
            )


class TestShippedValueIsBehaviourPreserving:
    """`min_bins_per_band: 1` is declared as a no-op ON PURPOSE (AC-19/RD-58).

    The mechanism and the measurement land now; the band-floor VALUE is a research
    decision (3 would drop every band below ~315 Hz) and is DEFERRED to E2. If that
    claim ever stops being true, these fail.
    """

    def test_base_declares_the_behaviour_preserving_floor(self) -> None:
        assert Config.load(_BASE).representation.params["min_bins_per_band"] == 1

    def test_production_ladder_is_27_bands_to_22627_hz(self, production_rep) -> None:
        d = production_rep.band_description
        assert production_rep.n_bands == 27
        assert d["represented_band_limit_hz"][1] == pytest.approx(22627.4, abs=0.1)


class TestUndeclaredPropertiesAreNowRecorded:
    """The three facts AC-19 found true but unstated."""

    def test_the_lowest_bands_hold_a_single_fft_bin(self, production_rep) -> None:
        d = production_rep.band_description
        single = [c for c, n in zip(d["center_freqs_hz"], d["bins_per_band"]) if n == 1]
        assert len(single) == 5, f"expected 5 single-bin bands, got {single}"
        assert max(single) < 130.0

    def test_center_freqs_is_irregular_and_says_so(self, production_rep) -> None:
        """Dropped bands break the ladder; `dropped_bands` records which."""
        d = production_rep.band_description
        ratios = np.diff(np.log2(d["center_freqs_hz"])) * 3.0
        assert not np.allclose(ratios, 1.0), "ladder unexpectedly regular"
        sub_minimum = [b for b in d["dropped_bands"] if "FFT bins" in b["reason"]]
        assert [round(b["center_hz"], 1) for b in sub_minimum][-3:] == [31.2, 39.4, 62.5]

    def test_the_band_above_nyquist_is_recorded_as_dropped(self, production_rep) -> None:
        """F-59: a candidate excluded by the Nyquist LOOP CONDITION never became a
        candidate, so it could not appear in `dropped_bands` — meta.json
        under-reported which bands were removed and why."""
        d = production_rep.band_description
        above = [b for b in d["dropped_bands"] if b["reason"] == "upper edge above Nyquist"]
        assert len(above) == 1, f"expected exactly one Nyquist-excluded rung, got {above}"
        assert above[0]["lo_hz"] == pytest.approx(d["represented_band_limit_hz"][1])

    def test_bins_outside_every_band_are_recorded(self, production_rep) -> None:
        """AC-31: this is a property of the BANK (bin count), not of any signal's
        power — the two coincide only for a white spectrum. Named accordingly."""
        frac = production_rep.band_description["uncovered_bin_fraction"]
        assert 0.05 < frac < 0.07, f"uncovered fraction moved: {frac}"


def _decaying_ir(rep, t60: float = 0.05, seconds: float = 0.5) -> np.ndarray:
    """An exponentially decaying noise IR long enough to span `min_db`.

    Deliberately steep and long: a short or slowly-decaying record never reaches
    the floor, so the clamp would be untested and every assertion below vacuous.
    """
    rng = np.random.default_rng(0)
    n = int(seconds * rep.sample_rate)
    t = np.arange(n) / rep.sample_rate
    return (np.exp(-6.908 * t / t60) * rng.standard_normal(n)).astype(np.float32)


class TestMinDbIsAnAbsoluteFloor:
    """AC-33: `min_db` is an ABSOLUTE dB clamp (re 1.0 in STFT power of the
    float32 IR), not a level below the per-scene peak.

    The distinction is invisible today — at unit gain 131.7 dB is retained below
    peak against the 35 dB T30 needs — but it changes silently if a second
    backend or a different `source_power` lands, because the absolute scale of an
    IR is the backend's to set. So the gain dependence is ASSERTED here: if a
    future change makes the floor peak-relative, this test fails and the
    disclosure has to move with it.
    """

    def _clamped_fraction(self, rep, gain: float) -> float:
        return float(
            (rep.encode(np.stack([_decaying_ir(rep) * gain])) <= rep.min_db + 1e-6)
            .float().mean()
        )

    def test_a_scene_on_the_floor_is_refused(self, production_rep) -> None:
        """AC-37's guard, asserted beside the property it protects.

        The gains below (0.01 … 100) sit INSIDE what the guard admits — measured,
        gain 0.01 leaves 54.21 dB of worst-band headroom against the declared
        50.0 — so those probes exercise the clamp without standing anything down.
        One more decade quieter (34.21 dB) is refused. Asserting both here keeps
        the two facts adjacent: the clamp is absolute, AND a scene that has slid
        onto it is rejected rather than silently encoded.
        """
        with pytest.raises(ValueError, match="min_db headroom guard"):
            production_rep.encode(np.stack([_decaying_ir(production_rep) * 1e-3]))

    def test_the_clamped_fraction_tracks_absolute_gain(self, production_rep) -> None:
        quiet = self._clamped_fraction(production_rep, 0.01)
        loud = self._clamped_fraction(production_rep, 100.0)
        assert quiet > loud, (
            f"clamped fraction did not fall with gain ({quiet} → {loud}); if the "
            f"floor was made peak-relative, update the AC-33 disclosure in "
            f"configs/representations/spectrogram.yaml with it"
        )

    def test_the_floor_is_the_declared_value_not_a_peak_offset(
        self, production_rep
    ) -> None:
        """A peak-relative floor would clamp at the same dB BELOW PEAK at every
        gain; an absolute one clamps at the same ABSOLUTE dB while the peak moves
        with the gain."""
        ir = _decaying_ir(production_rep)
        peaks = []
        for gain in (0.01, 1.0, 100.0):
            encoded = production_rep.encode(np.stack([ir * gain]))
            assert float(encoded.min()) == pytest.approx(production_rep.min_db)
            peaks.append(float(encoded.max()))
        # 20 dB of gain moves the peak 40 dB in power, so the retained range below
        # peak is NOT constant — the signature of an absolute floor.
        assert peaks[2] - peaks[0] == pytest.approx(80.0, abs=0.1)


class TestToneInBandKnownAnswer:
    """The probe AC-19 asked to become a known-answer test."""

    def test_a_500_hz_tone_lands_in_the_500_hz_band(self, production_rep) -> None:
        fractions = _band_fractions(production_rep, 500.0)
        assert fractions[_band_index(production_rep, 500.0)] > 0.99

    def test_in_band_fraction_degrades_toward_low_frequencies(
        self, production_rep
    ) -> None:
        measured = production_rep.describe_bands()["in_band_energy_fraction"]
        assert measured[_band_index(production_rep, 500.0)] > 0.99
        assert 0.93 < measured[_band_index(production_rep, 250.0)] < 0.97
        # One bin wide: this measures Hann leakage, not band content.
        assert 0.5 < measured[_band_index(production_rep, 125.0)] < 0.62

    def test_a_63_hz_tone_peaks_in_the_WRONG_band(self, production_rep) -> None:
        """Recorded, not fixed. A future band merge should make this test FAIL —
        that is the point: the change becomes visible instead of silent.
        """
        fractions = _band_fractions(production_rep, 63.0)
        peak = production_rep.center_freqs[int(np.argmax(fractions))]
        assert peak == pytest.approx(78.7, abs=0.1), (
            "the 63 Hz mis-peak changed — if this was deliberate, update the "
            "AC-19 disclosure and the E2 write-up with it"
        )
        assert 0.55 < fractions.max() < 0.62


class TestBandDescriptionReachesTheArtifact:
    """A per-band number must never be read without the evidence of what it is."""

    def test_describe_bands_covers_every_kept_band(self, production_rep) -> None:
        d = production_rep.describe_bands()
        n = production_rep.n_bands
        for key in ("center_freqs_hz", "band_edges_hz", "bins_per_band",
                    "in_band_energy_fraction"):
            assert len(d[key]) == n, f"{key} has {len(d[key])} entries for {n} bands"

    def test_preprocess_meta_records_it(self, tmp_path: Path) -> None:
        import json

        from amcd.data.preprocess import run_preprocess
        from amcd.scenes.generator import run_gen_scenes
        from amcd.simulators.render import run_render
        from tests.conftest import QUIET

        cfg = tiny_config(scenes={"n_id": 6})
        run_gen_scenes(cfg, tmp_path, QUIET)
        run_render(cfg, tmp_path, QUIET)
        run_preprocess(cfg, tmp_path, QUIET)

        meta = json.loads((tmp_path / "preprocessed" / "meta.json").read_text())
        desc = meta["band_description"]
        assert desc["center_freqs_hz"] == meta["center_freqs"]
        assert len(desc["in_band_energy_fraction"]) == meta["n_bands"]
        assert "uncovered_bin_fraction" in desc
